.travis.yml
Cartfile.resolved
Source/Background/BackgroundActivityFactory.swift
Source/Background/ZMBackgroundActivity.m
Source/Background/ZMSessionCancelTimer.m
Source/Public/ZMBackgroundActivity.h
Source/Public/ZMTransportSession.h
Source/Requests/ZMTransportRequest.m
Source/TransportSession/ZMTransportSession+internal.h
Source/TransportSession/ZMTransportSession.m
Tests/Source/Background/ZMBackgroundActivityTests.m
Tests/Source/Background/ZMSessionCancelTimerTests.m
Tests/Source/TransportSession/ZMTransportRequestSchedulerTests.m
Tests/Source/TransportSession/ZMTransportSessionTests.m
ZMTransport.xcodeproj/project.pbxproj

`ZMBackgroundActivity` is making use of `UIApplication` shared instance, which isn't thread safe and crash the application in some cases.
This PR fixes it by introducing a `BackgroundActivityFactory`, which will create a `ZMBackgroundActivity` and giving it the `ZMSGroupQueue` it needs to switch to when ending the activity.
There are couple of API changes that are breaking:
- `ZMTransportSession` receive an additional parameter at initialization, which is the `ZMSGroupQueue` the background activity will switch to (has to be the main thread group queue)
- To create a `ZMBackgroundActivity`, one would need to use the `BackgroundActivityFactory` for that purpose.

Fix crash on ending background activity

---

Source/Public/ZMUpdateEvent.h
Source/TransportEncoding/ZMUpdateEvent.m
Tests/Source/TransportEncoding/ZMUpdateEventTests.m

This PR applies the hotfix made on the 9.0.1 release.
`transient` argument added to the `ZMUpdateEvent` constructor.

Add transient argument to contructor

---

Source/Public/NSObject+ZMTransportEncoding.h
Source/Public/SwiftStructs+TransportEncoding.swift
Source/Public/ZMPushChannelConnection.h
Source/Public/ZMUpdateEvent.h
Source/TransportEncoding/ZMUpdateEvent.m

* Mark transportString on UUID as non null for better Swift integration

Mark transportString on UUID as nonnull

---

Source/URLSession/RequestLoopDetection.swift
Source/URLSession/ZMURLSession.m
Tests/Source/URLSession/RequestLoopDetectionTests.swift
ZMTransport.xcodeproj/project.pbxproj

We want to detect network requests loops that might cause the client to slow down and use too much network. This PR introduce the "RequestLoopDetection" class that keeps track of how often a path (from a URL) is being requested.
Also removed tracing, which we don't support anymore
This is an incomplete implementation, another PR will hook up the request loop detection with the transport session

Create RequestLoopDetection to detect request loops

---

Source/Public/ZMTransportRequest.h
Source/Public/ZMTransportSession.h
Source/Requests/ZMTransportRequest.m
Source/TransportSession/ZMTransportSession.m
Source/URLSession/RequestLoopDetection.swift
Tests/Source/Requests/ZMTransportRequestTests.m
Tests/Source/TransportSession/ZMTransportSessionTests.m
Tests/Source/URLSession/RequestLoopDetectionTests.swift

We want to track if there is any request loop in the requests generated by the transport session. We use the content debug information, if present, to distinguish between requests to the same conversation that have different content. We can't use the actual payload of the request because any re-encrypted repeated message will have a different content, however the plain text content, which is attached to the request object for debug purposes, will be the same so we use its hash.

Add loop detection callback on transport session

---

Source/URLSession/RequestLoopDetection.swift

Only consider the last minute, trigger after 10 repetitions, only keep the last 60 requests

Tweak loop detection parameters

---

Source/Public/ZMUpdateEvent.h
Source/TransportEncoding/ZMUpdateEvent.m
Tests/Source/TransportEncoding/ZMUpdateEventTests.m

When parsing the notification stream in response to a push notification we want to mark all notifications that occurred after a given UUID (type 1) as push event source.
To achieve this the `ZMUpdateEvent` array factory method now has an optional `pushStartingAfter` parameter, if provided, all events greater than or equal to the given uuid will be marked as `ZMUpdateEventSourcePushNotification` while older ones will remain `ZMUpdateEventSourceWebSocket`. The reasoning behind this is that we want treat these update events as if they would have been received through a push notification in order to generate a local push.
With this we also have the option to pass in a computed UUID that is a couple of minutes in the past. That would allow missed notifications to be fully displayed, e.g. if …

Add optional pushStartingAt threshold parameter to update event array constructor

---

Source/URLSession/ZMURLSession.m

* We check the progress of the file upload in `-[ZMURLSession(SessionDelegate) URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:]` and fail it if the new progress is less than the new one, which indicates that the request has been restarted.
* If this happens we complete the request and the request strategy can cancel the task by calling back into the transport session. However I noticed that the transcoder got notified multiple times and found the issue in `[NSURLSession getTasksWithCompletionHandler:]` taking long until the completion handler gets called, in the meantime we continue uploading the file, receive the progress callback and inform the transcoder again. 
* To avoid this scenario we now immediately cancel the task in the transport session, this way the …

Cancel task immediately if it should not be restarted

---

Source/TransportEncoding/NSData+Multipart.m
Tests/Source/TransportEncoding/NSData_MultipartTests.m

We would crash on unexpected header lines which we can avoid by adding a `NSNotFound`check.
https://wearezeta.atlassian.net/browse/ZIOS-7679

Add NSNotFound check to multipart header parsing

---

Source/Public/NSError+ZMTransportSession.h
Source/TransportSession/NSError+ZMTransportSession.m
Source/TransportSession/ZMTransportSession.m

Requests to /notifications often fail after 15 sec due to a timeout on the NSURLSession. We increase the timeout. When creating the request, each request gets an expiration date which is decreased when the request is not a background URLSession request but performed while the app is in the background. 
Also added some extra logging for NSURLResponse errors.

Increase timeout for voip session

---

Source/Public/ZMBackendEnvironment.h

* This initializer should not be used and thus is now marked as `NS_UNAVAILABLE`.

Mark parameterless init of ZMBackendEnvironment as unavailable

---

Source/Environments/ZMBackendEnvironment.m

* I forgot to remove the now unavailable `init` implementation that uses the standard `UserDefaults` which can lead to issues as we want to use the shared `UserDefaults` in extensions.

Remove unused init

---

Source/TransportEncoding/NSObject+ZMTransportEncoding.m
Tests/Source/TransportEncoding/NSObject_ZMTransportEncodingTests.m

- It was a good year.
- Backend returns 1970-01-01 as the last event time.

Allow parsing beggin of UNIX epoch as a valid time

---

Source/PushChannel/ZMNetworkSocket.m
Source/PushChannel/ZMStreamPairThread.h
Source/PushChannel/ZMStreamPairThread.m

When investigating a crash we have been having for quite a while I notice that crash logs contain many threads - sometimes 50 or 60. We have a custom `NSThread` subclass that is used for push channel input/output and is recreated every time the app comes back from background. Unfortunately it was not disposed correctly and stayed in memory.
It was not being released because it was waiting for events in the runloop without timeout (with `beforeDate:[NSDate distantFuture]`). This prevented the cancellation flag to be re-evaluated and kept the thread waiting and never had a chance to de-allocate.
Also removed a code that was checking for a property to exist which was never there and always evaluating to false.

Dispose push channel threads on close

---

Source/URLSession/RequestLoopDetection.swift

On the automation we see time to time that `/self` request is detected as a loop, but not always. After investigating this matter it looks like the self is requested several times, but those are valid requests (waiting for email confirmation for example). Not clear why the issue is showed up now.
Increase the threshold should unblock the automation, if it does not happen then we would need to look for some other solution.

Increase threshold to stop detecting self requests as a loop on sign in

---

Source/PushChannel/ZMStreamPairThread.m

Not removing them from runloop doesn't seem to make a difference, the `ZMStreamPairThread` still gets deallocated as expected.

Removing stream from runloop seems to crash when offline

---

Source/Public/ZMTransportResponse.h
Source/Requests/ZMTransportResponse.m
Tests/Source/Requests/ZMTransportResponseTests.m

Needed to avoid looping over the endpoints where we would not ever get the access too, for example:
1. User leaves the conversation.
1. Conversation is marked for some reason as to be re-fetched from the backend.
1. Backend returns 404.
-> App goes into the loop.

Indication of the errors that cannot be recovered by re-syncing

---

Source/Public/ZMPushChannelConnection.h
Source/Public/ZMReachability.h
Source/PushChannel/ZMNetworkSocket.m
Source/PushChannel/ZMPushChannelConnection.m
Source/PushChannel/ZMTransportPushChannel.m
Source/PushChannel/ZMWebSocket.h
Source/PushChannel/ZMWebSocket.m
Source/TransportSession/ZMTransportSession.m
Source/URLSession/ZMReachability.m
Tests/Source/PushChannel/ZMTransportPushChannelTests.m
Tests/Source/TransportSession/ZMTransportSessionTests.m

Several issues were fixed
(1) When the app launches without connectivity and then gains internet connection, we failed to open the push channel due to a missing access token. The access token was only renewed once a request was sent (e.g. by avs polling for calls). 
Solution: When reachability changed to maybeReachable and the accessToken expired, we send an accessTokenRequest.
(2) When the app has no internet we optimistically constantly try to reestablish the websocket. There is a race condition where we send a handshake frame while the app is offline and then regain connectivity. In this case the handshake is not sent again and the websocket not properly setup. 
Solution: When we regain internet and have an open websocket, we close the old one and create a new one.
(3) There were rare …

Fix push channel issues

---

WireTransport.xcodeproj/xcshareddata/xcschemes/WireTransport.xcscheme

Code coverage tracking didn't work with this framework. Our scheme was created before project rename and seems to be somewhat malformed - my suspicion is because scheme was named `WireTransport-ios`, but the product was `WireTransport`

Codecov: fix coverage tracking

---

Source/PushChannel/ZMNetworkSocket.m

High crash rate in recent release is indicating a possible issue with the line 236, where the `dispatch_sync` is called with `dataBufferIsolation` parameter. 
In the test project where the `dispatch_sync` is called with nil argument we received the same crash log as we see on user devices. Apparently if 2 writes are scheduled one after another right when the stream status is changing to error the first one is closing the connection and nullifying the `dataBufferIsolation`, and the second one is not falling in `outputStream.streamStatus == NSStreamStatusError`, since the value of `NSStreamStatusError` is 7, and if `outputStream` is nil then `outputStream.streamStatus` is resolved to 0.
Add extra guard to check that the `dataBufferIsolation` exists.

Extra guard to check if dataBufferIsolation exist

---

Source/Authentication/ZMAccessTokenHandler.m
Source/Background/BackgroundActivityFactory.swift
Source/PushChannel/ZMTransportPushChannel.m
Source/URLSession/ZMServerTrust.m

After creating an instance of `ZMTransportSession`, performing one request, waiting for response and tearing it down, only one instance left: a singleton.

Fix retain cycles and missing tear down calls

---

Source/URLSession/ZMServerTrust.m

It's all in the `__block`.
There is a "cleanup block" (the Obj-c version of Swift's `defer {}`), to make sure we release all variables in all conditional branches . However, the variables that are cleaned by the cleanup block are not declared `__block` so the block actually captures them by value when they are still not initialized, and when the block is executed, it does not release anything.

Fix memory leak in server trust verification

---

Source/Authentication/ZMPersistentCookieStorage.m

According to backend specifications we need to keep cookie label the same for all accounts on the device. This will prevent the situation when cookie label gets out of sync after force logout or logging in with a different method to an existing account.

Fix cookie label behaviour

---

Source/Public/WireTransport.h
Tests/Source/URLSession/TestTrustVerificator.swift
Tests/Source/URLSession/ZMServerTrustTests.m
WireTransport.xcodeproj/project.pbxproj

The trust tests for external hosts were failing because of outdated certificate fixtures which we store locally in order to not have to hit the network. However some of these certificates were updated at the beginning of July and will expire again in October. Because of these short lived certificates we now hit the network when testing checking the trust of external hosts.

Update tests to hit network for external host trust tests

---

Source/Public/ZMTransportRequest.h

* Use consistent naming in Swift using `NS_SWIFT_NAME`.

Unify method naming

---

Source/URLSession/ZMURLSession.m

Crash happens when we try to schedule the request on the torn down (invalidated) URL session.
Reference: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/NSURLSessionConcepts/NSURLSessionConcepts.html

Guard against invalidated session

---

Source/Public/ZMReachability.h
Source/Public/ZMTransportSession.h
Source/TransportSession/ZMTransportSession+internal.h
Source/TransportSession/ZMTransportSession.m
Source/URLSession/ZMReachability.m
Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift
Tests/Source/TransportSession/ZMTransportSessionTests.swift

In the `tearDown()` method of the `ZMTransportSession` class, the respective `tearDown()` method of the `ZMReachability` class wasn't called, causing a wrong deallocation of resources and then a crash.

fixed a bug where ZMReachability's tearDown wasn't called from ZMTransportSession

---

Source/TransportSession/ZMTransportSession.m

The reachability are shared between the unauthentication session and all user sessions, therefore it's should not be torn down.

Dont tear down reachability

---

Cartfile.resolved
Source/Public/ZMReachability.h
Source/Public/ZMTransportSession.h
Source/TransportSession/ZMTransportSession.m
Source/URLSession/ZMReachability.m
Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift
Tests/Source/TransportSession/ZMTransportSessionTests.m
Tests/Source/TransportSession/ZMTransportSessionTests.swift

Since we now will have multiple transport sessions running in parallel with one shared reachability
object, it will need to support having multiple observers.

Fix observing of reachability

---

Source/Authentication/ZMPersistentCookieStorage.m
Source/Public/ZMPersistentCookieStorage.h
Source/Public/ZMTransportSession.h
Source/Public/ZMURLSession.h
Source/TransportSession/ZMTransportSession.m
Source/URLSession/ZMURLSession.m
Tests/Source/TransportSession/ZMTransportSessionTests.swift

With multiple accounts logged in the image sent to inactive account would not be downloaded. 
Image downloading is always dispatched through background `URLSession`. With multiple accounts there are multiple background sessions. So in some cases the `ZMURLSession` would enqueue the request to the wrong background session. The request would still go through, but completion blocks would not get called.
Add user identifier to background session identifier and few more places to help debugging.

Mixed background sessions

---

Source/URLSession/ZMURLSession.m
Tests/Source/TransportSession/ZMTransportSessionTests.swift

- Recent change broke the `isBackgroundSession` detection.

Fixed background session detection

---

Source/Public/ZMTransportSession.h
Source/TransportSession/ZMTransportSession.m
Tests/Source/TransportSession/ZMTransportSessionTests.swift

Changed references to `sharedContainerIdentifier` to `applicationGroupIdentifier` in order to better reflect the behaviour of this variable into the app. Fixed typo.

changed sharedContainerIdentifier to applicationGroupIdentifier. fixed typo.

---

Source/Public/ZMUpdateEvent.h
Source/TransportEncoding/ZMUpdateEvent.m
Tests/Source/TransportEncoding/ZMUpdateEventTests.m

These events all belong to the V2 calling protocol which is no longer in use.

Remove unused calling related events

---

Cartfile.resolved
Source/PushChannel/ZMWebSocket.m

A hardcoded value was found for the WebSocket request header Sec-WebSocket-Key.
This value is a dummy value specified in RFC6455 4 . This RFC also makes it mandatory to always use a random base64 encoded nonce for the header value:
> The request MUST include a header field with the name |Sec-WebSocket-Key|. The value of this header field MUST be a nonce consisting of a randomly selected 16-byte value that has been base64-encoded (see Section 4 of [RFC4648]). The nonce MUST be selected randomly for each connection.
A random nonce is generated for each connection and request as specified by RFC6544, by using the new `generateWebSocketNonce` method.

ZIOS-9202: Added Websocket Nonce generator

---

Source/PushChannel/NetworkSocket.swift

We see in the Hockey that internal users who are using the new socket implementation are experiencing one in a while a crash when the input stream cannot send the callback to it's delegate. My idea is that the assert is not firing, since it's only crashing on the development, and the delegate reference is not nullified after the `NetworkSocket` is deallocated.
Potential solution is to additionally nullify the delegates in dealloc.

Potential fix for the stream crash

---

Source/Public/ZMTransportSession.h
Source/TransportSession/ZMTransportSession.m
Tests/Source/TransportSession/ZMTransportSessionTests.m

- Method implementation is not relevant to search.
- Now it's going to be used to fetch the service metadata or add service to the conversation.

Renamed enqeueSearchRequest to enqueueOneRequest

---

Source/Requests/ZMTransportRequest.m

I've added a filter for the MIME type `image/svg+xml` in `ZMTransportRequest.m`, since it cannot be considered as an image type from our side (see "Dependencies").
Needs releases with:

Added svg mime type to blacklist of non-image types

---

Source/TransportSession/UnauthenticatedTransportSession.swift

The logs of the unauthenticated transport session were not really readable:
```
Network [Unauthenticated] <---- Response: Optional([AnyHashable("Content-Type"): text/plain; 
charset=UTF-8, AnyHashable("Content-Length"): 20, AnyHashable("Connection"): keep-alive,
AnyHashable("Request-Id"): f33a7c4e4b9f78f7f1c23874b39f0746, AnyHashable("Access-Control-
Expose-Headers"): Request-Id, Location, AnyHashable("Strict-Transport-Security"): max-
age=31536000; preload, AnyHashable("Access-Control-Allow-Credentials"): true, 
AnyHashable("Server"): nginx, AnyHashable("Date"): Thu, 25 Jan 2018 09:48:46 GMT, 
AnyHashable("Content-Encoding"): gzip])
nil
```
This PR changes this to use the regular `description` of the requests and responses, also used by the regular, authenticated transport session.

Clean up unauthenticated network logs

---

Tests/Source/URLSession/ZMServerTrustTests.m

The certificate pinning test started to fail and was therefore disabled.
The *.wire.com certificate in the test fixture had expired
Update the certificate in the test and add instructions for how do this again in the future.

Update certificate and enable test again

---

Source/TransportEncoding/ZMUpdateEvent.m
Tests/Source/TransportEncoding/ZMUpdateEventTests.m

When removing a service user from conversation the API returns a result that has slightly different payload than usual. It has all the data wrapped inside another dictionary.
When creating a `ZMUpdateEvent` check if the event payload is wrapped inside `"event"` and then process it.

Update payload parsing for service users

---

Source/PushChannel/ZMTransportPushChannel.m
Tests/Source/PushChannel/ZMTransportPushChannelTests.m

When the app is in foreground and becomes offline (e.g. turning on airplane mode) the push channel is closed but will immediately try to be opened again. Since we are offline this is not possible and it is closed again. This causes a loop until the app goes in the background or we come back offline.
Check reachability when re-opening push channel and do nothing if internet is not reachable. We then later get callback when reachability changes and can open push channel.

Push channel opening and closing loop when offline

---

Source/PushChannel/ZMTransportPushChannel.m
Source/PushChannel/ZMWebSocket.m
Tests/Source/PushChannel/ZMWebSocketTests.m

The app is crashing sometimes when coming back from background.
This could be caused by the `NetworkSocket` object closed asynchronously in the `close()` method of `ZMWebSocket`.
Now we're closing the `NetworkSocket` synchronously in the proper queue, in order to avoid deadlocks. We're also closing the Push Channel while deallocating `ZMTransportPushChannel`.
- Since we don't have steps to reproduce this problem, other fixes could be needed. Let's try to merge so we could eventually collect crash logs.
- Thanks to @mikeger for the support!

ZIOS-9531: Fix crash in NetworkSocket: trying to dealloc socket from background thread

---

Source/PushChannel/NetworkSocket.swift
Source/PushChannel/ZMTransportPushChannel.m
Source/PushChannel/ZMWebSocket.m

PR related to network socket crash (ZIOS-9531). We're now deallocating the push channel in the `pushChannelDidClose:withResponse:` method of `ZMTransportPushChannel`. In addition, we're checking for the correct queue while closing the `NetworkSocket`.

ZIOS-9531: Moved push channel deallocation to ZMTransportPushChannel

---

Source/Public/ZMUpdateEvent.swift
Tests/Source/TransportEncoding/ZMUpdateEventTests.m

The `conversation.code-update` events were missing from the event stream.
The event type wasn't mapped.
Add `conversation.code-update` to the list of known events.

Add .conversationCodeUpdate to ZMUpdateEventType

---

Source/PushChannel/ZMTransportPushChannel.m
Tests/Source/PushChannel/ZMPushChannelConnectionTests.m

A possible fix for the new crash related to push channel closure. The behavior is similar to the previous crash. This time, the `pushChannelDidClose:withResponse:` method is called but, when we set `self.pushChannel = nil`, the channel seems to be still open. At that point, I'm trying to close the channel again. Theoretically, at the next iteration, the push channel should be closed.
@mikeger do you have any suggestions?

ZIOS-9743: Possible fix for closure of push channel

---

Source/PushChannel/ZMTransportPushChannel.h
Source/PushChannel/ZMTransportPushChannel.m
Source/TransportSession/ZMTransportSession.m
Tests/Source/Fakes.h
Tests/Source/Fakes.m
Tests/Source/PushChannel/ZMTransportPushChannelTests.m
Tests/Source/TransportSession/ZMTransportSessionTests.m

The push channel connection would sometimes assert in dealloc because it wasn't closed. 
After inspecting the threads involved I think this is a race condition created by the fact that the push channel methods are executed on both the sync thread and transport session thread. In particular the `establishConnection` method is executed on the transport session queue and the `pushChannelDidClose:withResponse:` is executed on the sync moc queue. If executed simultaneously this can lead to the situation that a push channel created and then immediately being deallocated.
Re-factor the push channel to only operate on the transport session queue.

Attempt to fix crash in push channel

---

Source/TransportSession/ZMTransportRequestScheduler.m
Tests/Source/TransportSession/ZMTransportRequestSchedulerTests.m

We used to set the scheduler state to offline when a request fails with an error other than 0, timeout or cancelled.
If at the same time reachability does not think we are actually offline we will only ever set the scheduler state to online again when reachability detects a connection, which won't happen as we are actually still online. A lot of the time the "messages stuck" issue happened when switching networks, I can easily imagine requests failing when switching network but reachability maybe already being back online by that time.
This is a first quick and easy approach to not have this two different sources of truth (a failed request flips the scheduler state to offline independent of the current reachability, but only reachability will flip it back). We now query the current …

Only set scheduler state to offline when reachability is offline as well

---

Cartfile.resolved
Source/Public/ZMReachability.h
Source/Public/ZMTransportRequestScheduler.h
Source/Public/ZMTransportSession.h
Source/Public/ZMURLSession.h
Source/Public/ZMURLSessionSwitch.h
Source/Requests/ZMExponentialBackoff.h
Source/TransportSession/UnauthenticatedTransportSession.swift
Source/TransportSession/ZMTransportSession+internal.h
Source/TransportSession/ZMTransportSession.m
Source/URLSession/ZMReachability.m
Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift
Tests/Source/TransportSession/ZMTransportSessionTests.swift

Transport had it's own protocol for `tearDown`, using the one from WireSystem instead
Needs releases with:

Using more general TearDownCapable protocol

---

Source/Requests/ZMTransportRequest.m
Tests/Source/Authentication/ZMTransportRequestLoggingTests.swift
WireTransport.xcodeproj/project.pbxproj

When logging into the app, the password of the user was visible inside logs of internal builds.
Every time we ask the `description` for an instance of `ZMTransportRequest`, if the `payload` field contains a key named `password`, the value for that key is replaced with `<redacted>`.

ZIOS-9978: Exclude user password from the network log

---

Cartfile.resolved
Source/Public/ZMTransportRequest.swift
Tests/Source/Requests/ZMTransportRequestTests.m
WireTransport.xcodeproj/project.pbxproj

Comply ZMTransportRequest to PrivateStringConvertible, removing the UUIDs from the request path. This code would be used in the upstream projects (sync engine, ...).

Private description for request

---

Source/URLSession/ZMReachability.m

`ZMReachability` assert and crash the upon switching accounts.
left old `_tornDown` flag was asserted instead of new `tornDownFlag`
Remove `_tornDown ` and assert on `tornDownFlag`

Fix wrong tornDown flag being checked on dealloc

---

Source/Public/BackendEnvironment.swift
Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift

We had a simple way to use custom backend endpoints, this PR tries to make it easier to customize without making changes in codebase.
`BackendEnvironment` is now `Decodable` and can be loaded from a JSON file. The initializer takes a Bundle that should contain a JSON file for each type of `WireEnvironmentType`. At the moment it's `production.json` and `staging.json`.

Made BackendEnvironment loadable from json

---

Source/Public/ZMUpdateEvent.swift

Added two new event types: "user.properties-set" and "user.properties-delete".
Also converted the ZMUpdateEventType to use CaseIterable. In this way we don't need _LAST case. Also added fixed indexes for the event types. Before we've been only able to add the new values to the end of the enum, since the values where stored as integers in the database.

New update event types: user properties

---

Source/TransportEncoding/ZMTransportCodec.m

We conform NSString to transport data protocol, but never actually implemented the sending of it.

Allow string-only payload

---

Source/Public/ZMUpdateEvent.swift

Add support for the event type `conversation.receipt-mode-update`

Add support for the event type conversation.receipt-mode-update

---

Source/Background/BackgroundActivityFactory.swift

Looking at the logs we see some weird discrepancies - logs have weird gaps in time. 
We should "flush" logs before finishing the background task, because the app could be suspended immediately after. 
Added call to `ZMSLog.sync()` which will make sure all things are written to disk before we finish the background task. Also tweaked few logs to have more info.

Improve logging on background tasks

---

Source/Background/BackgroundActivity.swift
Source/Background/BackgroundActivityFactory.swift
Source/Background/BackgroundActivityManager.swift
Tests/Source/Helpers/MockBackgroundActivityManager.swift

There were some improvements possible for background activity logging.
* Correctly printing the name of background task.
* Added time remaining for background processing
* Printing state of the app
* Added counter for background activities so it would be easier to match than pointer addresses used by default.

Improve background activities logging

---

Source/Background/BackgroundActivityFactory.swift
Source/Background/BackgroundActivityManager.swift

#118 has added logging remaining background time and app state. This API is main-thread only. Moved code around to deal with this.

Fix main thread warnings

---

Source/Background/BackgroundActivityFactory.swift
Tests/Source/Background/BackgroundActivityFactoryTests.swift

After studying the logs more it seems we were keeping around activities after background task expiration.
When expiration callback was called we should clear activities set to make sure none of them stay around for a new background task.

Remove expired activities

---

Source/Background/BackgroundActivity.swift
Source/Background/BackgroundActivityFactory.swift

The counter that should be unique for each new background task was not working correctly.
Save the counter value after incrementing instead of reading the static value. Also removed some logging on main queue because it was out of sync with the rest of log entries.

Improve logging for background tasks

---

Source/Public/Collections+ZMSafeTypes.swift
Source/TransportEncoding/NSObject+ZMTransportEncoding.m
Tests/Source/TransportEncoding/Collections+ZMTSafeTypesTests.m

On iOS 13 device, `dateForKey` of `NSDictionary` always return nil. 
Unknown, may be related to API changes.
rename the method to `dateFor` (for obj-c interface)

Fix: iOS 13 - dateForKey method always return nil

---

Source/Authentication/ZMPersistentCookieStorage.m
Source/Public/ZMPersistentCookieStorage.h
Tests/Source/Authentication/ZMPersistentCookieStorageTests.m

Add `authenticationCookieExpirationDate` to the `ZMPersistentCookieStorage` to allow us to validate cookies without contacting the server.

Add authenticationCookieExpirationDate to the cookie storage

---

Source/TransportSession/UnauthenticatedTransportSession.swift

There's no need for `UnauthenticatedTransportSession` to use a default session.
Configure it as ephemeral

Fix: UnauthenticatedTransportSession should be ephemeral

---

Source/TransportSession/UnauthenticatedTransportSession.swift
Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift

Add `enqueueOneTime(_ request: ZMTransportRequest)` to the unauthenticated transport session, which provides a way to perform single requests outside of the normal operation loop. This function already exists on the regular transport session.

[Feature] Add enqueueOneTime() to to unauthenticated transport session

---

Source/PushChannel/ZMWebSocketFrame.m
Tests/Source/PushChannel/ZMWebSocketTests.m

Some web socket servers were not letting the iOS client establish a WebSocket connection.
The WebSocket specification says that all frames sent a by client must have the `mask` bit set to `1`, if not the server must close the connection.
https://tools.ietf.org/html/rfc6455#section-5.1
The iOS client does not send any data over the WebSocket, except for the control frames (ping & pong). Even though we don't send any data with these control frames the `mask` bit must still be 1 to comply with the specification.
Set the `mask` bit to 1 for ping and pong frames. When the `mask` bit is set to `1` we also must include a [masking key](https://tools.ietf.org/html/rfc6455#section-5.2), but since we never include any payload I'm leaving it blank.
I choose not to implement masking for the sending of …

[Fix] WebSocket implementation not conforming to the RFC

---

Source/TransportSession/ZMTransportSession.m

We are seeing crashes triggered by a precondition that assert that we are executing on the correct managed object context.
example:
`[ZMMissingUpdateEventsTranscoder updateServerTimeDeltaWithTimestamp:]`
We suspect that the managed object context on which the `ZMMissingUpdateEventsTranscoder` operates has already been torn down when the request response arrives. When the context is torn down the keys in the `userInfo` are removed, which causes the `precondition(zm_isSyncContext)` to fail.
Wait until all the requests have been canceled before we remove the `userInfo` keys.

[Fix] Attempt to fix race condition when shutting an account

---

Source/Public/ZMTransportSession.h
Source/TransportSession/TransportSession.swift

Expose the `requestLoopDetectionCallback` on the `TransportSessionType`.

Expose the requestLoopDetectionCallback on the TransportSessionType

---

Source/Requests/RequestAvailableNotification.swift
Tests/Source/Requests/RequestAvailableNotificationTests.swift
WireTransport.xcodeproj/project.pbxproj

to allow the data-model to trigger a new request available notification `RequestAvailableNotification.notifyNewRequestsAvailable(nil)` I moved the `RequestAvailableNotification` class from the request-strategy to the transport layer.

[Feature]: Move RequestAvailableNotification from request-strategy

---

Source/Background/BackgroundActivityFactory.swift
Tests/Source/Background/BackgroundActivityFactoryTests.swift

Introduce `notifyWhenAllBackgroundActivitiesEnd()` on the `BackgroundActivityFactory`, which notifies the call when all background activities have ended or expired.

[Feature] Add notifyWhenAllBackgroundActivitiesEnd

---

Source/Background/BackgroundActivityFactory.swift

`notifyWhenAllBackgroundActivitiesEnd()` could run into a deadlock if another blocking operation was performed in the handler block. 
Async dispatch to the main queue before performing the handler block.

[Fix] potential deadlock by executing handler on the main queue

---

Source/TransportEncoding/NSObject+ZMTransportEncoding.m

`[NSDate transportString]` and `[NSDate dateWithTransportString]` are expensive calls, which is bad for event processing performance since it needs to convert many strings into dates.
The NSDate encoding/decoding is custom code relying on `strptime_l ` and `sscanf_l` which is not very optimised for speed.
Replace the custom encoding/decoding with a `NSDateFormatter` configured to parse ISO8601 dates.
This improves the `EventProcessingPerformanceTests` from  17s to 12s (~ 30% improvement).
Since iOS 10 there's also a `ISO8601DateFormatter` but we can't use it since we need the `.withFractionalSeconds` options which was introduced in iOS 11.

[Fix] Replace custom date encoder/decoder with NSDateFormatter

---

Source/Public/BackendEndpoints.swift
Source/Public/BackendEnvironment.swift
Source/Public/BackendEnvironmentProvider.swift
Tests/Source/Helpers/MockEnvironment.swift

It's not possible to switch to a custom backend.
After the introduction of the countlyURL in the `BackendEnvironment` all existing custom backend configurations will fail since they don't have the `countlyURL` defined.
Make the `countlyURL` optional.

[Fix] Make the countlyURL optional in the backend environment

---

Source/Requests/ZMTransportRequest.m

QA is triggering the request loop detection alert when receiving many messages in a short period of time.
The request loop detection is based on the HTTP request path and a hash based on the debug information of the request. This debug information is not set for every request though and there's no guarantee that it is uniquely identifying the request payload. 
For example when sending delivery receipts the debug information attached to the request is: "Confirmation Message". This doesn't include any IDs thus it will potentially trigger a request loop alert.
Compute the "content" has either on the complete binary data or the payload dictionary.
I would like to change the of `contentDebugInformationHash` to `contentHash` and make it private, but since that is a API breaking change I would …

[Fix] Request loop falsely being detected when receiving messages

---

Source/Authentication/ZMAccessTokenHandler.m
Source/Public/ZMTransportSession.h
Source/Public/ZMURLSession.h
Source/Public/ZMUserAgent.h
Source/Requests/ZMUserAgent.m
Source/TransportSession/UnauthenticatedTransportSession.swift
Source/TransportSession/ZMTransportSession+internal.h
Source/TransportSession/ZMTransportSession.m
Source/URLSession/ZMURLSession.m
Tests/Source/Helpers/ZMMockURLSession.swift
Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift
Tests/Source/TransportSession/ZMTransportSessionTests.m
Tests/Source/TransportSession/ZMTransportSessionTests.swift
Tests/Source/URLSession/ZMURLSessionTests.m

We set custom User-Agent on our requests from the transport session. This user agent includes the version number of the app, which is currently set by calling the static method:
```
[ZMUserAgent setWireAppVersion:]
```
Static method calls like this are hard to write tests for without a mocking framework which doesn't work in Swift.
- Set the user agent on the `URLSessionConfiguration` instead of manually setting on every request we schedule.
- Create the user agent string in the `ZMTransportSession` init using the already existing `appVersion` parameter
- Create the user agent string in the `UnauthenticatedSession` init by adding an `appVersion` parameter

[Refactor] Inject the app version for the user agent into the transport sessions

---

Source/URLSession/ZMURLSession.m
Tests/Source/URLSession/ZMURLSessionTests.m

Assets fetching fails with status 400 when running against a on premise installation of Wire.
```
[Network] <---- Response to GET /assets/v3/3-1-a8c0d976-61a6-49f2-9ef7-2d931d813b9f (status 400): <ZMTransportResponse: 0x600002989ae0> 400 {
"Accept-Ranges" = bytes;
"Content-Length" = 267;
"Content-Type" = "application/xml";
Date = "Thu, 14 Jan 2021 14:00:45 GMT";
Server = "nginx/1.17.8";
"Strict-Transport-Security" = "max-age=15724800; includeSubDomains";
Vary = Origin;
} (null)
```
We modify all redirects by adding authorisation headers. Redirects are mostly used by the backend when fetching assets where they will redirect the client to an CDN, this redirect already includes all the necessary authorisation and adding an additional one causes the on premise setup to reject the request. …

[Fix] Stop adding authorization headers to redirects since it interferes with asset fetching

---

Cartfile
Cartfile.resolved

Bump components due to a major release of `wire-ios-utilities`

Bump components due to major a release

---

Source/Public/ZMTransportRequestScheduler.h
Source/PushChannel/NativePushChannel.swift
Source/TransportSession/ZMTransportSession+internal.h
Source/TransportSession/ZMTransportSession.m

Websocket sometimes doesn't connect after returning from the background.
If the access token expired while the app was is in the the background the websocket task would never finish because it used and invalid access token.
Open the websocket using the scheduler like we do for the legacy websocket implementation. The scheduler will make sure that we have a valid access token.

[Fix] Websocket not connecting after the access token has expired

---

Source/TransportSession/ZMTransportSession.m

Sometimes all scheduled requests starts to timeout. The issue usually revolves it self after moving the the app into the background/foreground.
```
<ZMURLSession 0x28163b520> URLSession:task:didCompleteWithError: -> https://prod-nginz-https.wire.com/notifications?size=500&since=ca30c45a-c934-11eb-8005-22000ac389f3&client=67d81a150c0b3f6b (null), error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x283b4f000 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <E4962FC1-1A79-44F4-962E-2F625411CC83>.<196>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
"LocalDataTask …
```

[Fix] Sometimes all requests never finish and timeout

---

Source/PushChannel/NativePushChannel.swift
Source/PushChannel/ZMPushChannelType.h
Source/PushChannel/ZMTransportPushChannel.h
Source/PushChannel/ZMTransportPushChannel.m
Source/TransportSession/ZMTransportSession.m
Tests/Source/PushChannel/NativePushChannelTests+ServerTrust.swift
Tests/Source/TransportSession/ZMTransportSessionTests.m

Sometimes all scheduled requests starts to timeout. The issue usually revolves it self after moving the the app into the background/foreground.
```
<ZMURLSession 0x28163b520> URLSession:task:didCompleteWithError: -> https://prod-nginz-https.wire.com/notifications?size=500&since=ca30c45a-c934-11eb-8005-22000ac389f3&client=67d81a150c0b3f6b (null), error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x283b4f000 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <E4962FC1-1A79-44F4-962E-2F625411CC83>.<196>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
"LocalDataTask …
```

[Fix] Sometimes all requests never finish and timeout (2nd attempt)

---

Source/TransportEncoding/ZMTransportData.m

Mock transport session fails to process requests from The updated `MissingClientsRequestStrategy.
The updated `MissingClientsRequestStrategy` is creating the post payload from a struct and is therefore sent as string not as a `NSDictionary`. This becomes a problem in the mock transport session since it expecting the POST payload to be a NSDictionary. 
Implement `asDictionary` when ZMTransportData is a NSString.

[Chore] Fix failing integration tests 

---

Source/PushChannel/NativePushChannel.swift

We would not make more than one attempt to open the websocket connection
The failed websocket task was not nilled out, which prevented any further attempts to be made.
Implement the delegate for when the task fails and nil out the websocket task.

[Fix] nil out the websocket task when it fails so we can make another attempt

---

Source/TransportSession/UnauthenticatedTransportSession.swift

refactor deprecated `NSKeyedArchiver(forWritingWith:)` to `NSKeyedArchiver(requiringSecureCoding:)`

refactor deprecated NSKeyedArchiver(forWritingWith: data)

---

Source/Authentication/ZMPersistentCookieStorage.m
Tests/Source/TransportSession/HTTPCookie+HelperTests.swift

Refactor objc NSKeyedArchiver deprecated methods

Fix: refactor objc NSKeyedArchiver deprecated methods

---

Source/Authentication/ZMPersistentCookieStorage.m
Source/URLSession/ZMTaskIdentifier.h
Source/URLSession/ZMTaskIdentifier.m
Tests/Source/URLSession/ZMTaskIdentifierTests.m

Add `NSSecureCoding` to `ZMTaskIdentifier` to make it support new `NSKeyedUnarchiver unarchivedObjectOfClass:` instead of deprecated `NSKeyedUnarchiver unarchiveObjectWithData:`

refactor ZMTaskIdentifier to support NSKeyedUnarchiver unarchivedObjectOfClass

---

Source/Public/TrustData.swift
Source/URLSession/ZMServerTrust.h
Source/URLSession/ZMServerTrust.m

Remove the `_SecCertificateCopyPublicKey` wrapper for iOS 8 compatible and replace with `SecCertificateCopyKey`

remove ios 10 SecCertificateCopyPublicKey wrapper

---

Cartfile
Cartfile.resolved
Source/PushChannel/StarscreamPushChannel.swift
Source/TransportSession/ZMTransportSession.m
WireTransport.xcodeproj/project.pbxproj

Apples native websocket implementation sometimes starts blocking all other network requests.
After several days spent debugging this, the root cause is still unknown. I'll open a support ticket with Apple debug this further.
While we are waiting for feedback from Apple I'm adding an alternative websocket implementation based on the Starscream framework.
This is an API breaker since I'm adding a new Carthage dependency.

[Fix] Websocket blocking all network requests

---

Source/Authentication/ZMAccessTokenHandler.h
Source/Authentication/ZMAccessTokenHandler.m
Source/Public/WireTransport.h
Source/Public/ZMAPIVersion.h
Source/Public/ZMTransportRequest+AssetGet.h
Source/Public/ZMTransportRequest.h
Source/Public/ZMTransportResponse.h
Source/Requests/ZMTransportRequest.m
Source/Requests/ZMTransportResponse.m
Source/TransportSession/UnauthenticatedTransportSession.swift
Source/TransportSession/ZMTransportSession.m
Source/URLSession/ZMURLSession.m
Tests/Source/Authentication/ZMAccessTokenHandlerTests.m
Tests/Source/Authentication/ZMTransportRequestLoggingTests.swift
Tests/Source/Requests/ZMTransportRequestTests.m
Tests/Source/Requests/ZMTransportResponseTests.m
Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift
Tests/Source/TransportSession/ZMTransportSessionTests.m
Tests/Source/URLSession/ZMURLSessionTests.m
WireTransport.xcodeproj/project.pbxproj

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-481" title="FS-481" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-481</a>  [iOS] Pair requests and responses with api version
</td></table>
<br />
----
- The **PR Title**
- The **PR Description**
----
With API versioning, all requests are made to a versioned endpoint. In order to correctly process the response of a versioned request, we must also be able to identify the api version of the response.
This PR adds an api version property to both `ZMTransportRequest` and `ZMTransportResponse`.
No new tests have been added, but an assertion is made that when a request is completed with a response, the api versions must match. …

feat: add api version to requests and responses FS-481

---

Source/Public/APIVersion.swift
Source/Requests/ZMTransportRequest.m
Source/Requests/ZMTransportResponse.m

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-451" title="FS-451" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-451</a>  [iOS] Use the common version for all API calls
</td></table>
<br />
----
- The **PR Title**
- The **PR Description**
----
This PR adds api version 1, which is designates the federation endpoints as being available.
I added two small fixes in here too:
- the api version wasn't actually being stored in the transport responses.
- an error message had placeholder values incorrectly swapped.
----
----
----
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort …

feat: add api version v1 FS-451

---

Source/Public/ZMTransportRequest.h
Source/Requests/ZMTransportRequest.m

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-965" title="FS-965" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-965</a>  [iOS] Refactor `ZMTransportRequest` to allow setting Accept header values externally
</td></table>
<br />
----
- The **PR Title**
- The **PR Description**
----
- We need a way to be able to set the “accept” header when initialising a `ZMTransportRequest`.
- Added a new initialiser `ZMTransportRequest` that accepts the header type.
----
----
----
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

chore(mls): added init method to accept header values FS-965

---

Source/Public/ZMPersistentCookieStorage+Label.swift

<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1343" title="FS-1343" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-1343</a>  [iOS] Newly logged in client gets logged out
</td></table>
<br />
----
- The **PR Title**
- The **PR Description**
----
Sometimes a logged in client can get logged out if another client from the same device and account is deleted.
When logging in with a new client, we push up a cookie label that is unique for the device and app. **It is neither unique across accounts nor clients from the same account on the same device**. When a client is deleted, its associated cookies are deleted too, i.e all cookies that have the same cookie label.
This means …

fix: newly logged in client gets logged out FS-1343
