wireapp/wire-ios-transport

- .travis.yml
- Dangerfile
- Gemfile
- Gemfile.lock
- Tests/Source/TransportSession/ZMTransportRequestSchedulerTests.m
- Tests/Source/TransportSession/ZMTransportSessionTests.m
- Tests/Source/URLSession/ZMURLSessionTests.m
**What's in this PR?**
* Adds delays to flaky test that have been timing sensitive
* Add `Dangerfile` and `Gemfile`, update .travis.yml
> Add artificial delays / waits

- Source/Public/ZMTransportResponse.h
- Source/Public/ZMUpdateEvent.h
* This PR fixes wrong nullability annotations
> Fix wrong nullability annotations

- Source/Public/ZMTransportSession.h
* Update application parameter nullability as we don't have access to the shared `UIApplication` in the share extension
> Update application parameter nullability

- Source/Environments/ZMBackendEnvironment.m
- Source/Public/ZMBackendEnvironment.h
- Tests/Source/Environments/ZMBackendEnvironmentTests.m
- Removed the edge environment since it's not supported any more.
> Retire edge environment

- Source/URLSession/ZMServerTrust.m
SecKeyCreateFromData was iOS 10 only so we must use SecCertificateCreateFromData instead
> Fix iOS 8 & 9 support

- Source/Public/ZMUpdateEvent.h
- Source/TransportEncoding/ZMUpdateEvent.m
- Tests/Source/TransportEncoding/ZMUpdateEventTests.m
* Add `team.member-update` event.
> Add team.member-update event

- Source/TransportSession/ZMTransportSession.m
- Needed to catch messages getting stuck
> More logging for messages getting stuck

- Source/PushChannel/NetworkSocket.swift
- Tests/Source/PushChannel/ZMNetworkSocketTest.m
We noticed that the socket in Wire iOS client is sometimes being deallocated while still open. This used to cause the crash on internal.
This is going against the original architecture of the socket, where we used to always call close before deallocating the socket. 
It is possible to approach this problem from 2 points:
1. Allow deallocating the websocket and automatically close it.
2. Fix the iOS client to call close before deallocating the websocket. 
Both ways have pros and cons:
If we are going to enforce the close before dealloc, the solution appears initially as more solid, however the close should be still called from the correct thread, so it would not be enough to just call close before nullifying the reference. Also in ARC world it's not always easy to ensure the object …
> Auto-close the socket when deallocated

- Cartfile
- Cartfile.private
- Cartfile.resolved
- Source/Background/BackgroundActivityFactory.swift
- Source/Public/Collections+ZMSafeTypes.swift
- Source/Public/ZMPersistentCookieStorage+Label.swift
- Source/Public/ZMTransportRequest.swift
- Source/Public/ZMUpdateEvent.swift
- Source/PushChannel/NetworkSocket.swift
- Source/TransportSession/UnauthenticatedTransportSession.swift
- Source/URLSession/NSURLSessionConfiguration+Debugging.swift
- Source/URLSession/RequestLoopDetection.swift
- Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift
- Tests/Source/TransportSession/ZMTransportSessionTests.swift
- Tests/Source/URLSession/TestTrustVerificator.swift
- WireTransport.xcodeproj/project.pbxproj
> Swift 4 migration

- Source/TransportSession/UnauthenticatedTransportSession.swift
* Expose `UserInfo` to Objective-C.
> Expose UserInfo to Objective-C

- Source/Background/BackgroundActivityFactory.swift
We currently have a bug where the app never stops syncing. 
From the logs we see that we cannot create background task, the reason for it is not completely clear. Looking at code on UI it seems we do not call `resume()`. If we ever go into expiry mode, we will stay there until the app is killed.
Added more logs to see what is happening.
> Added logs for background task

- Source/Public/ZMPushChannelConnection.h
- Source/Public/ZMTransportSession.h
- Source/PushChannel/ZMPushChannelConnection.m
- Source/PushChannel/ZMTransportPushChannel.h
- Source/PushChannel/ZMTransportPushChannel.m
- Source/TransportSession/ZMTransportSession+internal.h
- Source/TransportSession/ZMTransportSession.m
- Tests/Source/Helpers/MockEnvironment.swift
- Tests/Source/PushChannel/ZMPushChannelConnectionTests.m
- Tests/Source/PushChannel/ZMTransportPushChannelTests.m
- Tests/Source/TransportSession/ZMTransportSessionTests.m
- Tests/Source/TransportSession/ZMTransportSessionTests.swift
- WireTransport.xcodeproj/project.pbxproj
To prepare for further changes we need to inject backend environment to various classes instead of plain URLs.
> Inject environment instead of URLs

- Source/URLSession/ZMURLSession.m
- Tests/Source/URLSession/ZMURLSessionTests.m
With #127 we have unintentionally removed part of code that was handling file upload.
Re-added code that was making a upload task with a file URL.
> Fix: Added back code that uploads file

- Cartfile
- Cartfile.private
- Cartfile.resolved
> Support for Xcode 10.1

- Source/Public/ZMUpdateEvent.swift
- Tests/Source/TransportEncoding/ZMUpdateEventTests.m
Add support for new user client event: `user.client-legal-hold-request`
> Add support for new user client event

- Source/Authentication/ZMKeychain.m
- Source/Authentication/ZMPersistentCookieStorage.m
- Source/Public/ZMKeychain.h
- Source/Public/ZMPersistentCookieStorage.h
- Tests/Source/Authentication/ZMAccessTokenHandlerTests.m
- Tests/Source/Authentication/ZMPersistentCookieStorageTests.m
Add method for checking if any authentication data is accessible in they keychain.
> Add method for checking if any authentication data is accessible

- Source/Public/ZMUpdateEvent.swift
- Tests/Source/TransportEncoding/ZMUpdateEventTests.m
> Add legal hold disabled event

- Source/Public/ZMTransportSession.h
- Source/TransportSession/TransportSession.swift
- Source/TransportSession/ZMTransportSession.m
- WireTransport.xcodeproj/project.pbxproj
Add TransportSessionType protocol to support easier mocking in Swift.
> Add TransportSessionType protocol

- Source/Public/ZMUpdateEvent.swift
- Tests/Source/TransportEncoding/ZMUpdateEventTests.m
Add support for `conversation.delete` event
> Add support for conversation.delete event

- Source/Public/ZMUpdateEvent.swift
- Tests/Source/TransportEncoding/ZMUpdateEventTests.m
Support for conversation deletion
> Add support for conversation.delete event (#148)

- Source/Public/BackendEnvironment+Defaults.swift
- Source/Public/BackendEnvironment.swift
- Tests/Source/URLSession/BackendEnvironmentTests.swift
Add function for migrating the BackendEnvironment between user defaults. This function will then be called from a hot fix patch in the sync engine.
> [Fix] Add function for migrating the BackendEnvironment between user defaults

- Source/Public/BackendEnvironment+Defaults.swift
- Source/Public/BackendEnvironment.swift
Adds a new environment type `qa-demo`
> [Feature] Support qa-demo environment

- Source/Public/BackendEnvironment+Defaults.swift
- Source/Public/BackendEnvironment.swift
- Added support for qa-demo-2 environment
> [Feature] Support qa-demo-2 environment

- Source/Public/BackendEndpoints.swift
- Source/Public/BackendEnvironment+Defaults.swift
- Source/Public/BackendEnvironment.swift
- Source/Public/BackendEnvironmentProvider.swift
- Tests/Resources/Backend.bundle/production.json
- Tests/Resources/Backend.bundle/staging.json
- Tests/Source/Helpers/MockEnvironment.swift
- Tests/Source/TransportSession/UnauthenticatedTransportSessionTests .swift
- Tests/Source/URLSession/BackendEnvironmentTests.swift
Support countly URL form `BackendEndpoints`
> countly URL support

- Cartfile
- Cartfile.resolved
> bump components

- Source/Authentication/AccessToken.swift
> dummy commit

- Cartfile
- Cartfile.resolved
bump for wireapp/wire-ios-utilities
> chore: bump wireapp/wire-ios-utilities

- Source/Authentication/ZMAccessTokenHandler.m
This is just an empty PR to trigger a new release.
> [Chore] Trigger
